// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Turnify.Infrastructure.Data;

#nullable disable

namespace Turnify.Infrastructure.Migrations
{
    [DbContext(typeof(TurnifyDbContext))]
    [Migration("20260425000000_AddEmployeeAvailableDays")]
    partial class AddEmployeeAvailableDays
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
